name: ECR-test

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Configure AWS credentials from Dev account 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: eu-central-1
          role-session-name: OIDCSession

      - name: Terraform Installation on Runner
        run: |
          aws s3 ls